# Service for the application

apiVersion: v1
kind: Service
metadata:
  name: devops-end2end
  labels:
    app: devops-end2end
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: devops-end2end
  type: ClusterIP